@extends('layouts.users')
@section('content')
<div class="container-fluid privacy_sec">
   <h3 class="text-center privacy_heading"><b>Privacy Policy</b></h3>
   <div class="ngo_conteiner">
   <p>We value the trust you place in us. That&#39;s why we insist upon the highest standards for secure
      transactions and User information privacy. Please read the following statement to learn about our
      information gathering and dissemination practices. The following Privacy Policy should be read along
      with the Weppl – Terms of Use for a full understanding of Weppl&#39;s practices as well as the Users
      responsibilities when interacting with the site <a href="http://www.weppl.org/">www.weppl.org</a>
   </p>
   <p>This Privacy Policy is published in accordance with the provisions of the Indian Information Technology Act, 2000 and the rules made thereunder, specifically, The Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal data or information) Rules, 2011 and the Information Technology (Intermediary Guidelines) Rules, 2011.</p>
   <p>All terms used in this Privacy Policy will have the same meaning and definition assigned to them in the Information Technology Act, 2000 and the rules made thereunder.</p>
   <p><b>Note:</b></p>
   <p>Our privacy policy is subject to change at any time without notice. To make sure you are aware of any changes, please review this policy periodically.</p>
   <p>By visiting this Website you agree to be bound by the terms and conditions of this Privacy Policy and the Terms of Use of the Webiste. If you do not agree please do not use or access the Website.</p>
   <p>By mere use of the Website, you expressly consent to our use and disclosure of your personal information in accordance with this Privacy Policy. This Privacy Policy is incorporated into and subject to the Terms of Use.</p>
   <h5><b>1. Collection of Personally Identifiable Information and other Information</b></h5>
   <p>When you use our Website, we collect and store your personal information, which is provided by you from time to time. Our primary goal in doing so is to provide you a safe, efficient, smooth and customized experience. This allows us to provide services and features that most likely meet your needs, and to customize our Website to make your experience safer and easier. More importantly, while doing so we collect personal information from you that we consider necessary for achieving this purpose.</p>
   <p>In general, you can browse the Website without telling us who you are or revealing any personal information about yourself. Once you give us your personal information, either by signing up through our portal or signing in through an associate API such as Google or Facebook, you are not anonymous to us. Where possible, we indicate which fields are required and which fields are optional. You always have the option to not provide information by choosing not to use a particular service or feature on the Website. We may automatically track certain information about you based upon your behaviour on our Website. We use this information to do internal research on our users' demographics, interests, and behaviour to better understand, protect and serve our users. This information is compiled and analysed on an aggregated basis. This information may include the URL that you just came from (whether this URL is on our Website or not), which URL you next go to (whether this URL is on our Website or not), your computer browser information, and your IP address.</p>
   <p>We use data collection devices such as "cookies" on certain pages of the Website to help analyse our web page flow, measure promotional effectiveness, and promote trust and safety. "Cookies" are small files placed on your hard drive that assist us in providing our services. We offer certain features that are only available through the use of a "cookie".
      We also use cookies to allow you to enter your password less frequently during a session. Cookies can also help us provide information that is targeted to your interests. Most cookies are "session cookies," meaning that they are automatically deleted from your hard drive at the end of a session. You are always free to decline our cookies if your browser permits. At this time, all features of the Website will work even if you disable cookies. However, in the future and in the event that we add certain new or improvised features and services to the Website, the Website or some parts of it may not be accessible if cookies are disabled. You may also be required to re-enter your password more frequently during a session.
   </p>
   <p>Additionally, you may encounter "cookies" or other similar devices on certain pages of the Website that are placed by third parties. We do not control the use of cookies by third parties.</p>
   <p>If you choose to donate or contribute on or through the Website, we collect information about your donations patterns and generally your usage behavior.</p>
   <p>If you transact with us (through making donations / contributions), we collect some additional information, such as a billing address, a credit / debit card number and a credit / debit card expiration date and/ or other payment instrument details and tracking information from cheques or money orders.</p>
   <p>If you choose to post messages on our message boards, chat rooms or other message areas or leave feedback, we will collect that information you provide to us. We retain this information as necessary to resolve disputes, provide User support and troubleshoot problems as permitted by law.</p>
   <p>If you send us personal correspondence, such as emails or letters, or if other users or third parties send us correspondence about your activities or postings on the Website, we may collect such information into a file specific to you.</p>
   <p>We collect personally identifiable information (email address, name, phone number, credit card / debit card / other payment instrument details, etc.) from you when you set up an account with us. While you can browse some sections of our Website without being a registered member, certain activities (such as making a donation / contribution) do require registration. We do use your contact information to send you information such as receipts, certificates, upcoming events, newsletters, etc. We also provide certain data to the Campaigner to interact with you and send you information of the type aforementioned as well as to complete certain transactions and fulfill commitments such as rewards, updates and the like.</p>
   <h5><b>2. Use of Demographic / Profile Data / Your Information</b></h5>
   <p>We use personal information to provide the services you request. To the extent we use your personal information to market to you, we will provide you the ability to opt-out of such uses. We use your personal information to resolve disputes; troubleshoot problems; help promote a safe service; collect money either by us or through an authorized payment gateway facility; measure User interests in Fundraisers hosted on our site, inform you about updates; customize your experience; detect and protect us against error, fraud and other criminal activity; enforce our terms and conditions; and as otherwise described to you at the time of collection.</p>
   <p>In our efforts to continually improve our product and service offerings, we collect and analyse demographic and profile data about our users' activity on our Website.</p>
   <p>We identify and use your IP address to help diagnose problems with our server, and to administer our Website. Your IP address is also used to help identify you and to gather broad demographic information.</p>
   <h5><b>3. Sharing of personal information</b></h5>
   <p>The following is information that we will not share with any third parties or disclose to any person other than as required by law; Sensitive Personal Data or Information of any person being the password, financial information such as Bank account or credit card or debit card or other payment instrument details, sexual orientation or any other sensitive personal information not essential for the continued use of the Website.</p>
   <p>We may share personal information with our other corporate and /or associate entities and affiliates to help detect and prevent identity theft, fraud and other potentially illegal acts and cyber security incidents; correlate related or multiple accounts to prevent abuse of our services; and to facilitate joint or co-branded services that you request where such services are provided by more than one associate entity. Those entities and affiliates may not market to you as a result of such sharing unless you explicitly opt-in.</p>
   <p>We may disclose personal information if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to summons, courtorders, or other legal process. We may disclose personal information to law enforcement offices, third party rights owners, or others in the good faith and belief that such disclosure is reasonably necessary to: enforce our Terms of Use or Privacy Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of our users or the general public.</p>
   <p>We and our affiliates will share, part with and allow any other business entity to use the personal information provided by the User to Weppl, in the event we (or our assets) plan to merge with, or be acquired by that business entity, or re-organization, amalgamation, restructuring of business. Should such a transaction occur that other business entity (or the new combined entity) will be required to follow this privacy policy with respect to your personal information.</p>
   <h5><b>4. Links to Other Sites</b></h5>
   <p>Our Website links to other websites that may collect personally identifiable information about you. Weppl is not responsible for the privacy practices or the content of those linked websites.</p>
   <h5><b>5. Security Precautions / Security Breach</b></h5>
   <p>Our Website has stringent security measures in place to protect the loss, misuse, and alteration of the information under our control. Whenever you change or access your account information, we offer the use of a secure server. Once your information is in our possession we adhere to strict security guidelines, protecting it against unauthorized access. Our web hosts, transaction affiliates etc, all use industry grade and standardized methods to protect your information from any misuse.</p>
   <p>If any User has sufficient reason to believe their Data as regarded as that which we do not share with third parties, has been compromised or there has been a breach of security due to a cyber security incident, you may write to us immediately at the contact details mentioned below so that we may take suitable measures to either rectify such a breach and inform the concerned authorities of a cyber security incident.</p>
   <p>To report an abuse on the Website, not being a cyber security incident, a User may click on the Report Abuse tab found at the bottom of the page and provide details of the abuse. Upon receiving such information Weppl will examine the abuse and take suitable and necessary steps to remedy it.</p>
   <h5><b>6. Review of Information / Account Deactivation / Removal of Information</b></h5>
   <p>If at any time a User wishes to review the information provided to Weppl at the time of registering with Weppl or at any time thereafter, you may do so by signing into your account and amending the same.</p>
   <p>We provide all users with the opportunity to opt-out of receiving non-essential (promotional, marketing-related) communications from us on behalf of our Campaigner, and from us in general, after setting up an account. All Users are also given the option of cancelling their User accounts and bringing to our attention their desire to discontinue the use of our services.</p>
   <p>If you want to deactivate your account or remove your contact information from all Weppl.org's lists and newsletters, please write to us at <a href="#">admin@weppl.org</a></p>
   <h5><b>7. Advertisements on Weppl.org</b></h5>
   <p>We use third-party advertising companies to serve ads when you visit our Website. These companies may use information (not including your name, address, email address, or telephone number and generally other information which may identify you personally) about your visits to this and other websites in order to provide advertisements about goods and services of interest to you.</p>
   <h5><b>8. Your Consent</b></h5>
   <p>By using the Website and/ or by providing your information, you consent to the collection and use of the information you disclose on the Website in accordance with this Privacy Policy, including but not limited to Your consent for sharing your information as per this privacy policy.</p>
   <p>If we decide to change our privacy policy, we will post those changes on this page so that you are always aware of what information we collect, how we use it, and under what circumstances we disclose it.</p>
   <p>The donors/contributors hereby permit Weppl to share their personal information such as name, email address, contact information to the respective Campaigner and beneficiaries of the donations made by the donors via Weppl.org</p>
   <h5><b>9. Retention of Information</b></h5>
   <p>Information provided by you to Weppl is processed, stored and retained through our servers and web hosts.</p>
   <p>Our web hosts and agency managing your information are compliant with IS/ISO/IEC27001 or an equivalent in standards of Security Techniques and Information Security Management System Requirements.</p>
   <h5><b>10. Grievance Officer</b></h5>
   <p>In accordance with Information Technology Act 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below:</p>
   <p><b>Mr. Amber Kumar Yadav</b></p>
   <p>Weppl Social Ventures Private Limited</p>
   <p>Email: <a href="#">admin@weppl.org</a></p>
   <p>Time: Mon - Sat (9:00 - 19:00)</p>
      <h5><b>11.Advertising Policies</b></h5>
      <p>We may use third-party advertising technologies that allow for the delivery of relevant content and advertising on our Platform, as well as on other websites you visit. The ads may be based on various factors such as the content of the page you are visiting, information you enter such as your age and gender, your searches, demographic data, user-generated content, and other information we collect from you. These ads may be based on your current activity or your activity over time and across other websites and online services and may be tailored to your interests.</p>
      <p>Also, third parties whose products or services are accessible or advertised on our Platform may place cookies or other tracking technologies on your computer, mobile phone, or other device to collect information about your use of the website as discussed above. We also allow other third parties (e.g., ad networks and ad servers such as Google Analytics, AdWords and others) to serve tailored ads to you on our website, other sites, and in other applications, and to access their own cookies or other tracking technologies on your computer, mobile phone, or other device you use to access the website. We may provide our customer information (such as a hashed version of your email addresses) to service providers, who may “match” this information in de-identified form to cookies (or mobile ad identifiers) and other proprietary IDs, in order to target or “retarget” you with ads when you visit other websites and mobile applications. (You may opt out of these many of these service providers as described in the next paragraph.)</p>
     <p> We neither have access to, nor does this Privacy Policy govern the use of cookies or other tracking technologies that may be placed on your computer, mobile phone, or other device you use to access our website by non-affiliated, third-party ad technology, ad servers, ad networks or any other non-affiliated third parties. Those parties that use these technologies may offer you a way to opt out of ad targeting as described below.</p>
      <p>If you receive tailored advertising on your computer through a web browser, you can learn more about such tailored browser advertising and how you can generally control cookies from being put on your computer to deliver tailored advertising, by visiting the European Interactive Digital Advertising Alliance Consumer <a href="http://www.youronlinechoices.com/uk/your-ad-choices" target="_blank">Ad Choices link </a>for EU based advertising or for US based advertising either: (i) the Network Advertising Initiative’s Consumer <a href="http://optout.networkadvertising.org/?c=1" target="_blank">Opt-Out link </a>or (ii) the Digital Advertising Alliance’s Consumer <a href="http://www.aboutads.info/choices/" target="_blank">Opt-Out link</a> to opt-out of receiving tailored advertising from companies that participate in those programs. To opt out of Google Analytics for display advertising or customize Google display network ads, you can visit the<a href="https://adssettings.google.com/authenticated" target="_blank"> Google Ads Settings page.</a></p>
      <p>Please note that to the extent advertising technology is integrated into our website or other websites that you visit, you may still receive advertisements even if you opt-out. In that case, the advertising will not be tailored to your interests. Also, we do not control any of the above opt-out links or whether any particular company chooses to participate in these opt-out programs. We are not responsible for any choices you make using these mechanisms or the continued availability or accuracy of these mechanisms.</p>
     <h5><b>12.Users in Europe</b></h5>
      <ul>  
       <li>Access. You have the right to request a copy of the information we are processing about you.
       </li>
      <li>Rectification. You have the right to have incomplete or inaccurate information that we process about you rectified.</li>
       <li>Deletion. You have the right to request that we delete information that we process about you, except we are not obliged to do so if we need to retain such data in order to comply with a legal obligation or to establish, exercise or defend legal claims.</li>
       <li>Restriction. You have the right to restrict our processing of your information where you believe such data to be inaccurate; our processing is unlawful; or that we no longer need to process such data for a particular purpose unless we are not able to delete the data due to a legal or other obligation or because you do not wish for us to delete it.</li>
      <li>Portability. You have the right to obtain information we hold about you in a structured, electronic format, and to transmit such data to another data controller, where this is (a) information that you have provided to us, and (b) if we are processing that data solely on the basis of your consent or to perform a contract with you.</li>
      <li>Objection. Where the legal basis for processing your information is our legitimate interest, you have the right to object to such processing on grounds relating to your particular situation. We will abide by your request unless we have compelling legitimate grounds for the processing which override your interests, or if we need to continue to process the data for the establishment, exercise or defense of a legal claim.</li>
      <li>Withdrawing consent. If you have consented to our processing of your information, you have the right to withdraw your consent at any time, free of charge. This includes where you wish to opt out from marketing messages.</li>
      </ul>
      <p>You can make a request to exercise any of these rights in relation to your information by sending the request to us at admin@weppl.org or mailing address set forth under "Contact Us” in the end of this page. For your own privacy and security, at our discretion, we may require you to provide your identity before providing the requested information. Please note that Weppl may take up to 30 days to fulfill such requests.</p>
      <p>You also have the right to lodge a complaint with the local data protection authority if you believe that we have not complied with applicable data protection laws. A list of local data protection authorities in European countries is available <a href="https://ec.europa.eu/justice/article-29/structure/data-protection-authorities/index_en.htm" target="_blank">here.</a></p>
      <h5><b>13.Changes to weppl's Privacy Plicy</b></h5>
      <p>The Services and our business may change from time to time. As a result, at times it may be necessary for Weppl to make changes to this Privacy Policy. Weppl reserves the right to update or modify this Privacy Policy at any time and from time to time. If you disagree with our revisions to the Privacy Policy, you may de-activate your account or discontinue the use of our Services. Please review this policy periodically, and especially before you provide us with any information through the Services. This Privacy Policy was last updated on the date indicated on top of this page. Your continued use of the Services after any changes or revisions to this Privacy Policy shall indicate your agreement with the terms of such revised Privacy Policy.</p>
      <p>If you are in Europe, you will not be required to agree to changes to this Privacy Policy, unless we specifically seek your consent.</p>
      <h5><b>14.Change Of Purpose</b></h5>
      <p>We will only use your personal data for the purposes for which we collected it, unless we reasonably consider that we need to use it for another reason and that reason is compatible with the original purpose. If you wish to get an explanation as to how the processing for the new purpose is compatible with the original purpose, please contact us.</p>
      <p>If we need to use your personal data for an unrelated purpose, we will notify you and we will explain the legal basis which allows us to do so.</p>
      <p>Please note that we may process your personal data without your knowledge or consent, in compliance with the above rules, where this is required or permitted by law.</p>

</div>
</div>
@endsection